package Pojo;
// Generated 12/08/2014 09:08:58 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * CategoriaHorasDocentes generated by hbm2java
 */
public class CategoriaHorasDocentes  implements java.io.Serializable {


     private int idCategoriaHorasDocentes;
     private String nombreCategoria;
     private String siglas;
     private String descripcion;
     private boolean estado;
     private String periodo;
     private Set profesorHorarioACumplirs = new HashSet(0);
     private Set profesorHorarioEkudemics = new HashSet(0);

    public CategoriaHorasDocentes() {
    }

	
    public CategoriaHorasDocentes(int idCategoriaHorasDocentes, String nombreCategoria, String siglas, String descripcion, boolean estado, String periodo) {
        this.idCategoriaHorasDocentes = idCategoriaHorasDocentes;
        this.nombreCategoria = nombreCategoria;
        this.siglas = siglas;
        this.descripcion = descripcion;
        this.estado = estado;
        this.periodo = periodo;
    }
    public CategoriaHorasDocentes(int idCategoriaHorasDocentes, String nombreCategoria, String siglas, String descripcion, boolean estado, String periodo, Set profesorHorarioACumplirs, Set profesorHorarioEkudemics) {
       this.idCategoriaHorasDocentes = idCategoriaHorasDocentes;
       this.nombreCategoria = nombreCategoria;
       this.siglas = siglas;
       this.descripcion = descripcion;
       this.estado = estado;
       this.periodo = periodo;
       this.profesorHorarioACumplirs = profesorHorarioACumplirs;
       this.profesorHorarioEkudemics = profesorHorarioEkudemics;
    }
   
    public int getIdCategoriaHorasDocentes() {
        return this.idCategoriaHorasDocentes;
    }
    
    public void setIdCategoriaHorasDocentes(int idCategoriaHorasDocentes) {
        this.idCategoriaHorasDocentes = idCategoriaHorasDocentes;
    }
    public String getNombreCategoria() {
        return this.nombreCategoria;
    }
    
    public void setNombreCategoria(String nombreCategoria) {
        this.nombreCategoria = nombreCategoria;
    }
    public String getSiglas() {
        return this.siglas;
    }
    
    public void setSiglas(String siglas) {
        this.siglas = siglas;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public String getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(String periodo) {
        this.periodo = periodo;
    }
    public Set getProfesorHorarioACumplirs() {
        return this.profesorHorarioACumplirs;
    }
    
    public void setProfesorHorarioACumplirs(Set profesorHorarioACumplirs) {
        this.profesorHorarioACumplirs = profesorHorarioACumplirs;
    }
    public Set getProfesorHorarioEkudemics() {
        return this.profesorHorarioEkudemics;
    }
    
    public void setProfesorHorarioEkudemics(Set profesorHorarioEkudemics) {
        this.profesorHorarioEkudemics = profesorHorarioEkudemics;
    }




}


