package Pojo;
// Generated 12/08/2014 09:08:58 AM by Hibernate Tools 3.6.0



/**
 * HorarioXCategoria generated by hbm2java
 */
public class HorarioXCategoria  implements java.io.Serializable {


     private int idHorarioCategoria;
     private ProfesorHorarioACumplir profesorHorarioACumplir;
     private String dia;
     private String horaInicio;
     private boolean estado;

    public HorarioXCategoria() {
    }

    public HorarioXCategoria(int idHorarioCategoria, ProfesorHorarioACumplir profesorHorarioACumplir, String dia, String horaInicio, boolean estado) {
       this.idHorarioCategoria = idHorarioCategoria;
       this.profesorHorarioACumplir = profesorHorarioACumplir;
       this.dia = dia;
       this.horaInicio = horaInicio;
       this.estado = estado;
    }
   
    public int getIdHorarioCategoria() {
        return this.idHorarioCategoria;
    }
    
    public void setIdHorarioCategoria(int idHorarioCategoria) {
        this.idHorarioCategoria = idHorarioCategoria;
    }
    public ProfesorHorarioACumplir getProfesorHorarioACumplir() {
        return this.profesorHorarioACumplir;
    }
    
    public void setProfesorHorarioACumplir(ProfesorHorarioACumplir profesorHorarioACumplir) {
        this.profesorHorarioACumplir = profesorHorarioACumplir;
    }
    public String getDia() {
        return this.dia;
    }
    
    public void setDia(String dia) {
        this.dia = dia;
    }
    public String getHoraInicio() {
        return this.horaInicio;
    }
    
    public void setHoraInicio(String horaInicio) {
        this.horaInicio = horaInicio;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }




}


