package Pojo;
// Generated 12/08/2014 09:08:58 AM by Hibernate Tools 3.6.0



/**
 * Inspectores generated by hbm2java
 */
public class Inspectores  implements java.io.Serializable {


     private int idInspector;
     private String primerNombre;
     private String segundoNombre;
     private String primerApellido;
     private String segundoApellido;
     private String cedula;

    public Inspectores() {
    }

	
    public Inspectores(int idInspector, String primerNombre, String segundoNombre, String primerApellido, String segundoApellido) {
        this.idInspector = idInspector;
        this.primerNombre = primerNombre;
        this.segundoNombre = segundoNombre;
        this.primerApellido = primerApellido;
        this.segundoApellido = segundoApellido;
    }
    public Inspectores(int idInspector, String primerNombre, String segundoNombre, String primerApellido, String segundoApellido, String cedula) {
       this.idInspector = idInspector;
       this.primerNombre = primerNombre;
       this.segundoNombre = segundoNombre;
       this.primerApellido = primerApellido;
       this.segundoApellido = segundoApellido;
       this.cedula = cedula;
    }
   
    public int getIdInspector() {
        return this.idInspector;
    }
    
    public void setIdInspector(int idInspector) {
        this.idInspector = idInspector;
    }
    public String getPrimerNombre() {
        return this.primerNombre;
    }
    
    public void setPrimerNombre(String primerNombre) {
        this.primerNombre = primerNombre;
    }
    public String getSegundoNombre() {
        return this.segundoNombre;
    }
    
    public void setSegundoNombre(String segundoNombre) {
        this.segundoNombre = segundoNombre;
    }
    public String getPrimerApellido() {
        return this.primerApellido;
    }
    
    public void setPrimerApellido(String primerApellido) {
        this.primerApellido = primerApellido;
    }
    public String getSegundoApellido() {
        return this.segundoApellido;
    }
    
    public void setSegundoApellido(String segundoApellido) {
        this.segundoApellido = segundoApellido;
    }
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }




}


