package Pojo;
// Generated 12/08/2014 09:08:58 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * JustificacionNovedades generated by hbm2java
 */
public class JustificacionNovedades  implements java.io.Serializable {


     private int idJustificacion;
     private String descripcion;
     private short horasDeJustificacion;
     private Date fechaCreacion;

    public JustificacionNovedades() {
    }

    public JustificacionNovedades(int idJustificacion, String descripcion, short horasDeJustificacion, Date fechaCreacion) {
       this.idJustificacion = idJustificacion;
       this.descripcion = descripcion;
       this.horasDeJustificacion = horasDeJustificacion;
       this.fechaCreacion = fechaCreacion;
    }
   
    public int getIdJustificacion() {
        return this.idJustificacion;
    }
    
    public void setIdJustificacion(int idJustificacion) {
        this.idJustificacion = idJustificacion;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public short getHorasDeJustificacion() {
        return this.horasDeJustificacion;
    }
    
    public void setHorasDeJustificacion(short horasDeJustificacion) {
        this.horasDeJustificacion = horasDeJustificacion;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }




}


