package Pojo;
// Generated 12/08/2014 09:08:58 AM by Hibernate Tools 3.6.0



/**
 * LogIngreso generated by hbm2java
 */
public class LogIngreso  implements java.io.Serializable {


     private LogIngresoId id;
     private UsuarioScd usuarioScd;
     private String accion;

    public LogIngreso() {
    }

    public LogIngreso(LogIngresoId id, UsuarioScd usuarioScd, String accion) {
       this.id = id;
       this.usuarioScd = usuarioScd;
       this.accion = accion;
    }
   
    public LogIngresoId getId() {
        return this.id;
    }
    
    public void setId(LogIngresoId id) {
        this.id = id;
    }
    public UsuarioScd getUsuarioScd() {
        return this.usuarioScd;
    }
    
    public void setUsuarioScd(UsuarioScd usuarioScd) {
        this.usuarioScd = usuarioScd;
    }
    public String getAccion() {
        return this.accion;
    }
    
    public void setAccion(String accion) {
        this.accion = accion;
    }




}


