package Pojo;
// Generated 12/08/2014 09:08:58 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * LogIngresoId generated by hbm2java
 */
public class LogIngresoId  implements java.io.Serializable {


     private Date fechaIngreso;
     private long fkIdUsuario;

    public LogIngresoId() {
    }

    public LogIngresoId(Date fechaIngreso, long fkIdUsuario) {
       this.fechaIngreso = fechaIngreso;
       this.fkIdUsuario = fkIdUsuario;
    }
   
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public long getFkIdUsuario() {
        return this.fkIdUsuario;
    }
    
    public void setFkIdUsuario(long fkIdUsuario) {
        this.fkIdUsuario = fkIdUsuario;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LogIngresoId) ) return false;
		 LogIngresoId castOther = ( LogIngresoId ) other; 
         
		 return ( (this.getFechaIngreso()==castOther.getFechaIngreso()) || ( this.getFechaIngreso()!=null && castOther.getFechaIngreso()!=null && this.getFechaIngreso().equals(castOther.getFechaIngreso()) ) )
 && (this.getFkIdUsuario()==castOther.getFkIdUsuario());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getFechaIngreso() == null ? 0 : this.getFechaIngreso().hashCode() );
         result = 37 * result + (int) this.getFkIdUsuario();
         return result;
   }   


}


