package Pojo;
// Generated 12/08/2014 09:08:58 AM by Hibernate Tools 3.6.0



/**
 * NovedadesHorario generated by hbm2java
 */
public class NovedadesHorario  implements java.io.Serializable {


     private int idNovedades;
     private TipoNovedad tipoNovedad;
     private ProfesorHorarioEkudemic profesorHorarioEkudemic;
     private short horasFalta;
     private String observacion;
     private short minAtraso;

    public NovedadesHorario() {
    }

    public NovedadesHorario(int idNovedades, TipoNovedad tipoNovedad, ProfesorHorarioEkudemic profesorHorarioEkudemic, short horasFalta, String observacion, short minAtraso) {
       this.idNovedades = idNovedades;
       this.tipoNovedad = tipoNovedad;
       this.profesorHorarioEkudemic = profesorHorarioEkudemic;
       this.horasFalta = horasFalta;
       this.observacion = observacion;
       this.minAtraso = minAtraso;
    }
   
    public int getIdNovedades() {
        return this.idNovedades;
    }
    
    public void setIdNovedades(int idNovedades) {
        this.idNovedades = idNovedades;
    }
    public TipoNovedad getTipoNovedad() {
        return this.tipoNovedad;
    }
    
    public void setTipoNovedad(TipoNovedad tipoNovedad) {
        this.tipoNovedad = tipoNovedad;
    }
    public ProfesorHorarioEkudemic getProfesorHorarioEkudemic() {
        return this.profesorHorarioEkudemic;
    }
    
    public void setProfesorHorarioEkudemic(ProfesorHorarioEkudemic profesorHorarioEkudemic) {
        this.profesorHorarioEkudemic = profesorHorarioEkudemic;
    }
    public short getHorasFalta() {
        return this.horasFalta;
    }
    
    public void setHorasFalta(short horasFalta) {
        this.horasFalta = horasFalta;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public short getMinAtraso() {
        return this.minAtraso;
    }
    
    public void setMinAtraso(short minAtraso) {
        this.minAtraso = minAtraso;
    }




}


