package Pojo;
// Generated 12/08/2014 09:08:58 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ProfesorHorarioEkudemic generated by hbm2java
 */
public class ProfesorHorarioEkudemic  implements java.io.Serializable {


     private int idProfesorHorarioEkudemic;
     private CategoriaHorasDocentes categoriaHorasDocentes;
     private String fkProfesor;
     private String fkMateria;
     private String nombreApellidoDocente;
     private Date fechaHorarioMateria;
     private char jornada;
     private String cursoParalelo;
     private Set novedadesHorarios = new HashSet(0);

    public ProfesorHorarioEkudemic() {
    }

	
    public ProfesorHorarioEkudemic(int idProfesorHorarioEkudemic, CategoriaHorasDocentes categoriaHorasDocentes, String fkProfesor, String fkMateria, String nombreApellidoDocente, Date fechaHorarioMateria, char jornada, String cursoParalelo) {
        this.idProfesorHorarioEkudemic = idProfesorHorarioEkudemic;
        this.categoriaHorasDocentes = categoriaHorasDocentes;
        this.fkProfesor = fkProfesor;
        this.fkMateria = fkMateria;
        this.nombreApellidoDocente = nombreApellidoDocente;
        this.fechaHorarioMateria = fechaHorarioMateria;
        this.jornada = jornada;
        this.cursoParalelo = cursoParalelo;
    }
    public ProfesorHorarioEkudemic(int idProfesorHorarioEkudemic, CategoriaHorasDocentes categoriaHorasDocentes, String fkProfesor, String fkMateria, String nombreApellidoDocente, Date fechaHorarioMateria, char jornada, String cursoParalelo, Set novedadesHorarios) {
       this.idProfesorHorarioEkudemic = idProfesorHorarioEkudemic;
       this.categoriaHorasDocentes = categoriaHorasDocentes;
       this.fkProfesor = fkProfesor;
       this.fkMateria = fkMateria;
       this.nombreApellidoDocente = nombreApellidoDocente;
       this.fechaHorarioMateria = fechaHorarioMateria;
       this.jornada = jornada;
       this.cursoParalelo = cursoParalelo;
       this.novedadesHorarios = novedadesHorarios;
    }
   
    public int getIdProfesorHorarioEkudemic() {
        return this.idProfesorHorarioEkudemic;
    }
    
    public void setIdProfesorHorarioEkudemic(int idProfesorHorarioEkudemic) {
        this.idProfesorHorarioEkudemic = idProfesorHorarioEkudemic;
    }
    public CategoriaHorasDocentes getCategoriaHorasDocentes() {
        return this.categoriaHorasDocentes;
    }
    
    public void setCategoriaHorasDocentes(CategoriaHorasDocentes categoriaHorasDocentes) {
        this.categoriaHorasDocentes = categoriaHorasDocentes;
    }
    public String getFkProfesor() {
        return this.fkProfesor;
    }
    
    public void setFkProfesor(String fkProfesor) {
        this.fkProfesor = fkProfesor;
    }
    public String getFkMateria() {
        return this.fkMateria;
    }
    
    public void setFkMateria(String fkMateria) {
        this.fkMateria = fkMateria;
    }
    public String getNombreApellidoDocente() {
        return this.nombreApellidoDocente;
    }
    
    public void setNombreApellidoDocente(String nombreApellidoDocente) {
        this.nombreApellidoDocente = nombreApellidoDocente;
    }
    public Date getFechaHorarioMateria() {
        return this.fechaHorarioMateria;
    }
    
    public void setFechaHorarioMateria(Date fechaHorarioMateria) {
        this.fechaHorarioMateria = fechaHorarioMateria;
    }
    public char getJornada() {
        return this.jornada;
    }
    
    public void setJornada(char jornada) {
        this.jornada = jornada;
    }
    public String getCursoParalelo() {
        return this.cursoParalelo;
    }
    
    public void setCursoParalelo(String cursoParalelo) {
        this.cursoParalelo = cursoParalelo;
    }
    public Set getNovedadesHorarios() {
        return this.novedadesHorarios;
    }
    
    public void setNovedadesHorarios(Set novedadesHorarios) {
        this.novedadesHorarios = novedadesHorarios;
    }




}


