package Pojo;
// Generated 12/08/2014 09:08:58 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ProfesorHorarioACumplir generated by hbm2java
 */
public class ProfesorHorarioACumplir  implements java.io.Serializable {


     private int idPhc;
     private CategoriaHorasDocentes categoriaHorasDocentes;
     private String cedulaDocente;
     private Date fechaInicio;
     private Date fechaFin;
     private boolean estado;
     private short cantidadHoras;
     private String facultad;
     private Set horarioXCategorias = new HashSet(0);

    public ProfesorHorarioACumplir() {
    }

	
    public ProfesorHorarioACumplir(int idPhc, CategoriaHorasDocentes categoriaHorasDocentes, String cedulaDocente, Date fechaInicio, Date fechaFin, boolean estado, short cantidadHoras, String facultad) {
        this.idPhc = idPhc;
        this.categoriaHorasDocentes = categoriaHorasDocentes;
        this.cedulaDocente = cedulaDocente;
        this.fechaInicio = fechaInicio;
        this.fechaFin = fechaFin;
        this.estado = estado;
        this.cantidadHoras = cantidadHoras;
        this.facultad = facultad;
    }
    public ProfesorHorarioACumplir(int idPhc, CategoriaHorasDocentes categoriaHorasDocentes, String cedulaDocente, Date fechaInicio, Date fechaFin, boolean estado, short cantidadHoras, String facultad, Set horarioXCategorias) {
       this.idPhc = idPhc;
       this.categoriaHorasDocentes = categoriaHorasDocentes;
       this.cedulaDocente = cedulaDocente;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.estado = estado;
       this.cantidadHoras = cantidadHoras;
       this.facultad = facultad;
       this.horarioXCategorias = horarioXCategorias;
    }
   
    public int getIdPhc() {
        return this.idPhc;
    }
    
    public void setIdPhc(int idPhc) {
        this.idPhc = idPhc;
    }
    public CategoriaHorasDocentes getCategoriaHorasDocentes() {
        return this.categoriaHorasDocentes;
    }
    
    public void setCategoriaHorasDocentes(CategoriaHorasDocentes categoriaHorasDocentes) {
        this.categoriaHorasDocentes = categoriaHorasDocentes;
    }
    public String getCedulaDocente() {
        return this.cedulaDocente;
    }
    
    public void setCedulaDocente(String cedulaDocente) {
        this.cedulaDocente = cedulaDocente;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public short getCantidadHoras() {
        return this.cantidadHoras;
    }
    
    public void setCantidadHoras(short cantidadHoras) {
        this.cantidadHoras = cantidadHoras;
    }
    public String getFacultad() {
        return this.facultad;
    }
    
    public void setFacultad(String facultad) {
        this.facultad = facultad;
    }
    public Set getHorarioXCategorias() {
        return this.horarioXCategorias;
    }
    
    public void setHorarioXCategorias(Set horarioXCategorias) {
        this.horarioXCategorias = horarioXCategorias;
    }




}


