package Pojo;
// Generated 12/08/2014 09:08:58 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * TipoNovedad generated by hbm2java
 */
public class TipoNovedad  implements java.io.Serializable {


     private int idTipoNovedad;
     private String nombreDelTipo;
     private String descripcion;
     private Set novedadesHorarios = new HashSet(0);

    public TipoNovedad() {
    }

	
    public TipoNovedad(int idTipoNovedad, String nombreDelTipo, String descripcion) {
        this.idTipoNovedad = idTipoNovedad;
        this.nombreDelTipo = nombreDelTipo;
        this.descripcion = descripcion;
    }
    public TipoNovedad(int idTipoNovedad, String nombreDelTipo, String descripcion, Set novedadesHorarios) {
       this.idTipoNovedad = idTipoNovedad;
       this.nombreDelTipo = nombreDelTipo;
       this.descripcion = descripcion;
       this.novedadesHorarios = novedadesHorarios;
    }
   
    public int getIdTipoNovedad() {
        return this.idTipoNovedad;
    }
    
    public void setIdTipoNovedad(int idTipoNovedad) {
        this.idTipoNovedad = idTipoNovedad;
    }
    public String getNombreDelTipo() {
        return this.nombreDelTipo;
    }
    
    public void setNombreDelTipo(String nombreDelTipo) {
        this.nombreDelTipo = nombreDelTipo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getNovedadesHorarios() {
        return this.novedadesHorarios;
    }
    
    public void setNovedadesHorarios(Set novedadesHorarios) {
        this.novedadesHorarios = novedadesHorarios;
    }




}


