package Pojo;
// Generated 12/08/2014 09:08:58 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * UsuarioScd generated by hbm2java
 */
public class UsuarioScd  implements java.io.Serializable {


     private int idUsuario;
     private String usuario;
     private String password;
     private char rol;
     private boolean estado;
     private String email;
     private Set logIngresos = new HashSet(0);

    public UsuarioScd() {
    }

	
    public UsuarioScd(int idUsuario, String usuario, char rol, boolean estado, String email) {
        this.idUsuario = idUsuario;
        this.usuario = usuario;
        this.rol = rol;
        this.estado = estado;
        this.email = email;
    }
    public UsuarioScd(int idUsuario, String usuario, String password, char rol, boolean estado, String email, Set logIngresos) {
       this.idUsuario = idUsuario;
       this.usuario = usuario;
       this.password = password;
       this.rol = rol;
       this.estado = estado;
       this.email = email;
       this.logIngresos = logIngresos;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public char getRol() {
        return this.rol;
    }
    
    public void setRol(char rol) {
        this.rol = rol;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getLogIngresos() {
        return this.logIngresos;
    }
    
    public void setLogIngresos(Set logIngresos) {
        this.logIngresos = logIngresos;
    }




}


