package Pojo;
// Generated 12/08/2014 09:08:58 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * ViInfoHorariosEkudemicId generated by hbm2java
 */
public class ViInfoHorariosEkudemicId  implements java.io.Serializable {


     private String facultad;
     private String jornada;
     private String dia;
     private Date hora;
     private String curso;
     private String materia;
     private String cedulaDocente;
     private String nombreDocente;
     private String apellidoDocente;
     private Integer anio;

    public ViInfoHorariosEkudemicId() {
    }

    public ViInfoHorariosEkudemicId(String facultad, String jornada, String dia, Date hora, String curso, String materia, String cedulaDocente, String nombreDocente, String apellidoDocente, Integer anio) {
       this.facultad = facultad;
       this.jornada = jornada;
       this.dia = dia;
       this.hora = hora;
       this.curso = curso;
       this.materia = materia;
       this.cedulaDocente = cedulaDocente;
       this.nombreDocente = nombreDocente;
       this.apellidoDocente = apellidoDocente;
       this.anio = anio;
    }
   
    public String getFacultad() {
        return this.facultad;
    }
    
    public void setFacultad(String facultad) {
        this.facultad = facultad;
    }
    public String getJornada() {
        return this.jornada;
    }
    
    public void setJornada(String jornada) {
        this.jornada = jornada;
    }
    public String getDia() {
        return this.dia;
    }
    
    public void setDia(String dia) {
        this.dia = dia;
    }
    public Date getHora() {
        return this.hora;
    }
    
    public void setHora(Date hora) {
        this.hora = hora;
    }
    public String getCurso() {
        return this.curso;
    }
    
    public void setCurso(String curso) {
        this.curso = curso;
    }
    public String getMateria() {
        return this.materia;
    }
    
    public void setMateria(String materia) {
        this.materia = materia;
    }
    public String getCedulaDocente() {
        return this.cedulaDocente;
    }
    
    public void setCedulaDocente(String cedulaDocente) {
        this.cedulaDocente = cedulaDocente;
    }
    public String getNombreDocente() {
        return this.nombreDocente;
    }
    
    public void setNombreDocente(String nombreDocente) {
        this.nombreDocente = nombreDocente;
    }
    public String getApellidoDocente() {
        return this.apellidoDocente;
    }
    
    public void setApellidoDocente(String apellidoDocente) {
        this.apellidoDocente = apellidoDocente;
    }
    public Integer getAnio() {
        return this.anio;
    }
    
    public void setAnio(Integer anio) {
        this.anio = anio;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ViInfoHorariosEkudemicId) ) return false;
		 ViInfoHorariosEkudemicId castOther = ( ViInfoHorariosEkudemicId ) other; 
         
		 return ( (this.getFacultad()==castOther.getFacultad()) || ( this.getFacultad()!=null && castOther.getFacultad()!=null && this.getFacultad().equals(castOther.getFacultad()) ) )
 && ( (this.getJornada()==castOther.getJornada()) || ( this.getJornada()!=null && castOther.getJornada()!=null && this.getJornada().equals(castOther.getJornada()) ) )
 && ( (this.getDia()==castOther.getDia()) || ( this.getDia()!=null && castOther.getDia()!=null && this.getDia().equals(castOther.getDia()) ) )
 && ( (this.getHora()==castOther.getHora()) || ( this.getHora()!=null && castOther.getHora()!=null && this.getHora().equals(castOther.getHora()) ) )
 && ( (this.getCurso()==castOther.getCurso()) || ( this.getCurso()!=null && castOther.getCurso()!=null && this.getCurso().equals(castOther.getCurso()) ) )
 && ( (this.getMateria()==castOther.getMateria()) || ( this.getMateria()!=null && castOther.getMateria()!=null && this.getMateria().equals(castOther.getMateria()) ) )
 && ( (this.getCedulaDocente()==castOther.getCedulaDocente()) || ( this.getCedulaDocente()!=null && castOther.getCedulaDocente()!=null && this.getCedulaDocente().equals(castOther.getCedulaDocente()) ) )
 && ( (this.getNombreDocente()==castOther.getNombreDocente()) || ( this.getNombreDocente()!=null && castOther.getNombreDocente()!=null && this.getNombreDocente().equals(castOther.getNombreDocente()) ) )
 && ( (this.getApellidoDocente()==castOther.getApellidoDocente()) || ( this.getApellidoDocente()!=null && castOther.getApellidoDocente()!=null && this.getApellidoDocente().equals(castOther.getApellidoDocente()) ) )
 && ( (this.getAnio()==castOther.getAnio()) || ( this.getAnio()!=null && castOther.getAnio()!=null && this.getAnio().equals(castOther.getAnio()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getFacultad() == null ? 0 : this.getFacultad().hashCode() );
         result = 37 * result + ( getJornada() == null ? 0 : this.getJornada().hashCode() );
         result = 37 * result + ( getDia() == null ? 0 : this.getDia().hashCode() );
         result = 37 * result + ( getHora() == null ? 0 : this.getHora().hashCode() );
         result = 37 * result + ( getCurso() == null ? 0 : this.getCurso().hashCode() );
         result = 37 * result + ( getMateria() == null ? 0 : this.getMateria().hashCode() );
         result = 37 * result + ( getCedulaDocente() == null ? 0 : this.getCedulaDocente().hashCode() );
         result = 37 * result + ( getNombreDocente() == null ? 0 : this.getNombreDocente().hashCode() );
         result = 37 * result + ( getApellidoDocente() == null ? 0 : this.getApellidoDocente().hashCode() );
         result = 37 * result + ( getAnio() == null ? 0 : this.getAnio().hashCode() );
         return result;
   }   


}


