package Pojo;
// Generated 12/08/2014 09:08:58 AM by Hibernate Tools 3.6.0



/**
 * ViInfoHorariosEkudemic generated by hbm2java
 */
public class ViInfoHorariosEkudemic  implements java.io.Serializable {


     private ViInfoHorariosEkudemicId id;

    public ViInfoHorariosEkudemic() {
    }

    public ViInfoHorariosEkudemic(ViInfoHorariosEkudemicId id) {
       this.id = id;
    }
   
    public ViInfoHorariosEkudemicId getId() {
        return this.id;
    }
    
    public void setId(ViInfoHorariosEkudemicId id) {
        this.id = id;
    }




}


